version: '3.7'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=serftopia
      - POSTGRES_PASSWORD=mikekoth
      - POSTGRES_DB=serftopia_dev
  front:
    build: ./frontend
    tty: true
    command: npm run start
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - web
  widget:
    build: ./widget
    command: npm run start
    volumes:
      - './widget:/widget'
      - '/widget/node_modules'
    ports:
      - 9000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  postgres_data: