# Generated by Django 3.0.2 on 2020-03-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200322_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
