# Generated by Django 3.0.2 on 2020-03-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('groups', 'For groups'), ('person', 'For persons')], default='groups', max_length=255),
        ),
    ]
