# Generated by Django 3.0.2 on 2020-03-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('service', '0005_auto_20200324_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorystaffconnector',
            unique_together={('category', 'staff')},
        ),
    ]
