# Generated by Django 3.0.2 on 2020-03-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('service', '0006_auto_20200324_1522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicestaffconnector',
            unique_together={('service', 'staff')},
        ),
    ]
