# Generated by Django 3.0.2 on 2020-05-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_description'),
        ('service', '0008_auto_20200429_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestaffconnector',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_staff_field', to='staff.Staff'),
        ),
    ]
