# Generated by Django 3.0.2 on 2020-05-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20200505_1948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicestaffconnector',
            unique_together=set(),
        ),
    ]
