# Generated by Django 3.0.2 on 2020-04-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200423_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_social_link', to='company.Company'),
        ),
    ]
