# Generated by Django 3.0.2 on 2020-03-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200324_1523'),
        ('staff', '0001_initial'),
        ('client', '0003_client_user'),
        ('sale', '0003_sale_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='guests_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='saleclientconnector',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client'),
        ),
        migrations.AlterUniqueTogether(
            name='saleclientconnector',
            unique_together={('sale', 'client')},
        ),
        migrations.CreateModel(
            name='SaleServiceConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_service', to='sale.Sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Service')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Staff')),
            ],
        ),
    ]
