# Generated by Django 3.0.2 on 2020-03-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20200324_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='service',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='staff',
        ),
    ]
