# Generated by Django 3.0.2 on 2020-03-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20200324_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleserviceconnector',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
