# Generated by Django 3.0.2 on 2020-03-24 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_saleserviceconnector_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleclientconnector',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_client', to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='saleserviceconnector',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_service', to='sale.Sale'),
        ),
    ]
