# Generated by Django 3.0.2 on 2020-04-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('sale', '0008_auto_20200324_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='guests_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='saleserviceconnector',
            name='date',
        ),
        migrations.RemoveField(
            model_name='saleserviceconnector',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='saleserviceconnector',
            name='start_time',
        ),
        migrations.AddField(
            model_name='sale',
            name='endDate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='sale',
            name='startDate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SaleClientConnector',
        ),
    ]
