# Generated by Django 3.0.2 on 2020-05-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_auto_20200429_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
