# Generated by Django 3.0.2 on 2020-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200505_2012'),
        ('sale', '0010_auto_20200507_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='services',
            field=models.ManyToManyField(to='service.Service'),
        ),
    ]
