# Generated by Django 3.0.2 on 2020-05-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200429_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
