# Generated by Django 3.0.2 on 2020-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_company_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscompanypermissions',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
