# Generated by Django 3.0.2 on 2020-04-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_company_permissions', '0002_userscompanypermissions_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscompanypermissions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
