# Generated by Django 3.0.2 on 2020-04-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_company_permissions', '0004_group_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_permission_group', to='users_company_permissions.Group'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_permission_permission', to='users_company_permissions.Permission'),
        ),
        migrations.AlterField(
            model_name='userscompanypermissions',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company_group_field', to='users_company_permissions.Group'),
        ),
    ]
