# Generated by Django 3.0.2 on 2020-04-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_company_permissions', '0006_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='access_type',
            field=models.CharField(choices=[('watching', 'Watching type'), ('editing', 'Editing type')], default='watching', max_length=10),
        ),
    ]
