# Generated by Django 3.0.2 on 2020-04-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_company_permissions', '0009_auto_20200429_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscompanypermissions',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
